# The DocPad Configuration File
# It is simply a CoffeeScript Object which is parsed by CSON
docpadConfig = {

    # =================================
    # DocPad Configuration

    # Change the port DocPad uses from the default 9778 to 8080
    port: 8080


    # =================================
    # Template Data
    # These are variables that will be accessible via our templates

    # =================================
    # Template Data
    # These are variables that will be accessible via our templates
    # To access one of these within our templates, refer to the FAQ: https://github.com/bevry/docpad/wiki/FAQ

    templateData:

        # Specify some site properties
        site:
            # The production url of our website
            url: "http://edzillion.com"

            # The default title of our website
            title: "edzillion"

            # The website author's name
            author: "ed murphy"

            # The website author's email
            email: "edzillion@gmail.com"

            scripts: [
                'libs/jquery-1.8.3.js',
                'libs/modernizr.custom.94543.js',
                'js/main.js'
            ]
            
            # The website heading to be displayed on the page
            heading: 'code, code ... afrobeat'

            # The website subheading to be displayed on the page
            subheading: '''
                <t render="html.coffee">
                    link = @getPreparedLink.bind(@)
                    text """
                        This site was built from scratch using #{link 'docpad'} with the help of #{link 'nodejs'}, #{link 'modernizr'} and #{link 'jquery'}. You can  #{link 'githubsource'} or #{link 'themakingofthissite'}. 
                        """
                </t>
                '''

            # Footer
            footnote: """
                This website was created with <t>links.bevry</t>’s <t>links.docpad</t>
                """
            copyright: """
                Your chosen license should go here... Not sure what a license is? Refer to the <code>README.md</code> file included in this website.
                """

            # The website description (for SEO)
            description: """
                When your website appears in search results in say Google, the text here will be shown underneath your website's title.
                """

            # The website keywords (for SEO) separated by commas
            keywords: """
                place, your, website, keywoards, here, keep, them, related, to, the, content, of, your, website
                """

            # The website analytics codes for various servers
            analytics:
                google: 'UA-37571865-1'

            #3rd party services / apis
            services:
                disqus: 'edzillion'
                
            # Specify some feed available for the visitors of our website
            feeds: [
                    # This is the feed generated by our DocPad website
                    # It contains all the posts, you can find the source file in src/documents/atom.xml.eco
                    href: 'http://your-website.com/atom.xml'
                    name: 'Blog Posts'
                ,
                    # DocPad's Twitter Stream
                    # Included here as an example that you can include feed from anywhere
                    href: 'https://api.twitter.com/1/statuses/user_timeline.atom?screen_name=docpad&count=20&include_entities=true&include_rts=true'
                    name: 'DocPad Tweets'
            ]

            # Do you have social accounts?
            # Mention them here and our layout will include them in the sidebar
            # If you specify a feed for the Feedr plugin (specified later on)
            # then we will pull in their feed data too for recognised services
            social:
                # DocPad's Twitter Profile
                # Included here as an example
                twitter:
                    url: 'https://twitter.com/docpad'

                # Balupton's GitHub Profile
                # Included here as an example
                github:
                    url: 'https://github.com/balupton'

                # Balupton's Vimeo Profile
                # Included here as an example
                vimeo:
                    url: 'https://vimeo.com/balupton'

                # Balupton's Flickr Profile
                # Included here as an example
                flickr:
                    url: 'http://www.flickr.com/people/balupton/'


        # -----------------------------
        # Common links used throughout the website

        links:
            docpad: '<a href="https://github.com/bevry/docpad" title="Visit on GitHub">DocPad</a>'
            opensource: '<a href="http://en.wikipedia.org/wiki/Open-source_software" title="Visit on Wikipedia">Open-Source</a>'
            html5: '<a href="http://en.wikipedia.org/wiki/HTML5" title="Visit on Wikipedia">HTML5</a>'
            javascript: '<a href="http://en.wikipedia.org/wiki/JavaScript" title="Visit on Wikipedia">JavaScript</a>'
            nodejs: '<a href="http://nodejs.org/" title="Visit Website">Node.js</a>'
            author: '<a href="http://edzillion.com" title="Visit Website">Ed Murphy</a>'
            cclicense: '<a href="http://creativecommons.org/licenses/by/3.0/" title="Visit Website">Creative Commons Attribution License</a>'
            mitlicense: '<a href="http://creativecommons.org/licenses/MIT/" title="Visit Website">MIT License</a>'
            email: '<a href="mailto:edzillion@gmail.com" title="Email me">Email</a>'
            simplelifeforms: '<a href="http://www.simplelifeforms.com/" title="Visit Website">Simple Lifeforms</a>'
            vampirecities: '<a href="http://www.vampirecities.com/" title="Visit Website">Vampire Cities</a>'
            discogs: '<a href="http://www.discogs.com/seller/edzillion" title="Visit Website">Discogs</a>'
            soundcloud: '<a href="https://soundcloud.com/edzillion" title="Visit Website">SoundCloud</a>'
            github: '<a href="https://github.com/edzillion" title="Visit Website">GitHub</a>'
            twitter: '<a href="https://twitter.com/edzillion" title="Visit Website">Twitter</a>'
            linkedin: '<a href="https://www.linkedin.com/in/edwardtmurphy" title="Visit Website">LinkedIn</a>'
            github: '<a href="https://github.com/edzillion" title="Visit Website">GitHub</a>'
            alanodea: '<a href="http://www.alanodea.com" title="Visit Website">GitHub</a>'
            twoc: '<a href="https://soundcloud.com/t-woc" title="Visit Website">t-woc</a>'
            homoludo: '<a href="http://www.olwill.com/" title="Visit Website">homoludo</a>'
            githubsource: '<a href="https://github.com/edzillion/edzillion.com">view the source on github</a>'
            themakingofthissite: '<a href="http://edzillion.com/the-making-of-the-making-of.html">read my notes on developing this site</a>'

        # -----------------------------
        # Helper Functions


        # Link Helper
        getPreparedLink: (name) ->
            link = @site.links[name]
            renderedLink = """
                <a href="#{link.url}" title="#{link.title}">#{link.text}</a>
                """
            return renderedLink

        # Get the site title
        # Often we would like to specify particular formatting to our page's title
        # we can apply that formatting here
        getPageTitle: ->
            # if we have a document title, then we should use that and suffix the site's title onto it
            if @document.title
                "#{@document.title} | #{@site.title}"
            # if our document does not have it's own title, then we should just use the site's title
            else
                @site.title

        # Return an article's categories in css class format
        getItemBoxClasses: (article) ->
            classString = 'itembox' 
            # if we have any categories add them to a string 
            if article.categories                
                classString += ' '+article.categories.join(' ');
                classString
            else
                classString   

        getItemBoxSymbols: (article) ->
            symbolsString = ''
            if article.categories
                for cat in article.categories
                    switch cat
                        when 'games'
                            symbolsString += '&#48;'
                        when 'code'
                            symbolsString += '&#114;'
                        when 'music'
                            symbolsString += '&#81;'
                        when 'design'
                            symbolsString += '&#71;'
                        when 'comment'
                            symbolsString += '&#95;'
                        when 'video'
                            symbolsString += '&#75;'
                        when 'android'
                            symbolsString += '&#108;'
                         
                symbolsString
            else
                symbolsString = '&#181;'
                symbolsString



    # =================================
    # Collections
    # These are special collections that our website makes available to us

    collections:
        # This collection named 'articles' fetches the documents with the 'layout' property set to 'article'
        articles: (database) ->
            database.findAllLive({layout: 'article.html.eco'}, {date:-1})
        games: (database) ->
            database.findAllLive({categories: $has: ['games']}, {date:-1})
        code: (database) ->
            database.findAllLive({categories: $has: ['code']}, {date:-1})
        design: (database) ->
            database.findAllLive({categories: $has: ['design']}, {date:-1})
                   
}
# Export our DocPad Configuration
module.exports = docpadConfig